// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int Ntime = Integer.parseInt(args[0]);
		int aboveHalf = 0;
		int belowHalf = 0;

		for (int i = 0; i < Ntime; i++) {
			Double functionValue = Math.random();

		if (functionValue > 0.5) {
			aboveHalf++;
		} else {
			belowHalf++;
			}
		}
		
		System.out.println("> 0.5: " + aboveHalf + " times");
		System.out.println("<= 0.5: " + belowHalf + " times");
		
		if (belowHalf > 0) {
			Double rasio = (double) aboveHalf / (double) belowHalf;
			System.out.println("Rasio: " + rasio);
		}
	
	}
}
